---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    dnf:
      update_cache: yes

  - name: Install httpd package
    dnf:
      name: httpd
      state: latest

  - name: Install git
    dnf:
      name: git
      state: latest

  - name: Install nginx
    dnf:
      name: nginx
      state: latest
