---

- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution == "RedHat"

  - name: install web services package
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "RedHat"

  - name: add php support for apache
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "RedHat"
