---

- hosts: all
  become: true
  pre_tasks:
  
  - name: Install updates (Fedora)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Fedora"

  - name: Install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: web_servers
  become: true
  tasks:

  - name: Install apache and php for Ubuntu servers
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"  

  - name: Install apache and php for Fedora servers
    tags: apache,fedora,httpd
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Fedora"  


- hosts: db_servers
  become: true
  tasks:

  - name: Install mariadb package (Fedora)
    tags: fedora,db,mariadb
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "Fedora"

  - name: Install mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"  


- hosts: file_servers
  become: true
  tasks:

  - name: Install samba package
    tags: samba
    package:
      name: samba
      state: latest
